[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
asyncio_mode = auto
addopts = --disable-warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::Warning
