"""Add CheckIn table

Revision ID: 1c19775a7574
Revises: 2a0cb1c9eff2
Create Date: 2026-06-28 12:49:05.834010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c19775a7574'
down_revision: Union[str, Sequence[str], None] = '2a0cb1c9eff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
                    sa.Column('member_id', sa.String(
                        length=36), nullable=False),
                    sa.Column('checked_in_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('note', sa.String(length=255), nullable=True),
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    # ### end Alembic commands ###
