"""add created_by to subscriptions

Revision ID: 2a0cb1c9eff2
Revises: 457f6de7f1c5
Create Date: 2026-06-26 10:07:53.084452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2a0cb1c9eff2"
down_revision: Union[str, Sequence[str], None] = "457f6de7f1c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("created_by", sa.String(), nullable=True))
    op.create_foreign_key(
        "fk_subscriptions_created_by_users",
        "subscriptions",
        "users",
        ["created_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_subscriptions_created_by_users",
        "subscriptions",
        type_="foreignkey",
    )
    op.drop_column("subscriptions", "created_by")
    # ### end Alembic commands ###
