"""Add member_subscription table

Revision ID: 53f35ad06c3e
Revises: a6820318f356
Create Date: 2026-06-26 13:10:38.801585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f35ad06c3e'
down_revision: Union[str, Sequence[str], None] = 'a6820318f356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('member_subscriptions_member_id_key'), 'member_subscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('member_subscriptions_member_id_key'), 'member_subscriptions', ['member_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
