"""update type role user

Revision ID: eb6f2c6e767b
Revises: 54b6adc19e5f
Create Date: 2026-06-23 13:53:18.781399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6f2c6e767b'
down_revision: Union[str, Sequence[str], None] = '54b6adc19e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DO $$ BEGIN CREATE TYPE userrole AS ENUM ('admin', 'staff'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("admin", "staff", name="userrole"),
        existing_nullable=False,
        postgresql_using="role::userrole",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum("admin", "staff", name="userrole"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
